DELIMITER $$
CREATE DEFINER=`etl`@`%` FUNCTION `fn_etl_date`() RETURNS datetime
BEGIN
DECLARE dt datetime;

	SET dt = CASE WHEN CURTIME() >= '13:00' THEN NOW() ELSE DATE_SUB(NOW(), INTERVAL 1 DAY) END;

RETURN dt;
END$$
DELIMITER ;
