CREATE TABLE `lu_day` (
  `day_id_sk` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `day_id` int(10) unsigned NOT NULL,
  `day_date` date NOT NULL,
  `month_id` int(6) unsigned DEFAULT NULL,
  `quarter_id` smallint(5) unsigned DEFAULT NULL,
  `year_id` smallint(4) unsigned DEFAULT NULL,
  `prev_day_date` date DEFAULT NULL,
  `next_day_date` date DEFAULT NULL,
  `prev_day_id` int(6) unsigned DEFAULT NULL,
  `next_day_id` int(6) unsigned DEFAULT NULL,
  `lm_day_date` date DEFAULT NULL,
  `lq_day_date` date DEFAULT NULL,
  `ly_day_date` date DEFAULT NULL,
  `week_id` int(6) unsigned DEFAULT NULL,
  `first_day_week_flag` bit(1) DEFAULT NULL,
  `last_day_week_flag` bit(1) DEFAULT NULL,
  `GMT_diff` int(11) DEFAULT NULL,
  `last_update_datetime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`day_id_sk`),
  UNIQUE KEY `day_date_UNIQUE` (`day_date`),
  UNIQUE KEY `day_id_UNIQUE` (`day_id`),
  KEY `midx` (`month_id`),
  KEY `didx` (`day_id`),
  KEY `idx_lu_day_week_id` (`week_id`)
) ENGINE=MyISAM AUTO_INCREMENT=4019 DEFAULT CHARSET=utf8;
