CREATE TABLE master_dim.`lu_month` (
  `lu_month_sk` int(11) NOT NULL AUTO_INCREMENT,
  `month_id` int(11) unsigned NOT NULL,
  `month_date` date DEFAULT NULL,
  `current_month_flag` bit(1) DEFAULT b'0',
  `month_end_date` date DEFAULT NULL,
  `month_end_day_id` int(10) unsigned DEFAULT NULL,
  `month_desc` varchar(50) DEFAULT NULL,
  `month_of_year` tinyint(3) unsigned DEFAULT NULL,
  `month_of_year_desc` varchar(45) DEFAULT NULL,
  `quarter_id` smallint(5) unsigned DEFAULT NULL,
  `year_id` smallint(4) unsigned DEFAULT NULL,
  `month_duration` tinyint(2) unsigned DEFAULT NULL,
  `prev_month_id` int(6) unsigned DEFAULT NULL,
  `next_month_id` int(6) unsigned DEFAULT NULL,
  `renew_month_id` int(6) unsigned DEFAULT NULL,
  `lq_month_id` int(6) unsigned DEFAULT NULL,
  `ly_month_id` int(6) unsigned DEFAULT NULL,
  `last_update_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`lu_month_sk`),
  UNIQUE KEY `month_id_UNIQUE` (`month_id`),
  UNIQUE KEY `lu_month_sk_UNIQUE` (`lu_month_sk`),
  KEY `fk_lu_month_lu_year1` (`year_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
